name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::053855110563:role/github-actions-lindolfomoizinho-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "lindolfomoizinho-sa-east-1-terraform-statefile "
      aws-lock-dynamodb-table: "lindolfomoizinho-sa-east-1-terraform-lock"